import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { resolve } from "node:path";
// Generated by scripts/build-server.mjs before the development server starts.
// @ts-ignore -- compiled server modules retain their source types in server/.
import { apiMiddleware } from "./.server/server/http.js";
export default defineConfig({
  plugins: [
    react(),
    {
      name: "fieldfit-api",
      configureServer(server) {
        const port = Number(process.env.PORT ?? 5173);
        const origin = new URL(
          process.env.PUBLIC_ORIGIN ?? "http://127.0.0.1:" + port,
        ).origin;
        server.middlewares.use(apiMiddleware(origin));
      },
    },
  ],
  resolve: { alias: { "@": resolve(".") } },
  server: {
    host: "127.0.0.1",
    port: Number(process.env.PORT ?? 5173),
    strictPort: true,
    fs: {
      deny: [
        ".env*",
        "**/.data/**",
        "**/.wrangler/**",
        "**/.git/**",
        "**/server/**",
        "**/.server/**",
        "**/lib/question-bank.ts",
        "**/db/**",
        "**/scripts/**",
      ],
    },
  },
  build: { outDir: "dist/client" },
});
