import type { Question } from './assessment';
const q=(id:string,cap:number,p:string[],o:string[][],points:number[],explanation:string):Question=>({id,cap,prompt:{en:p[0],ms:p[1],zh:p[2]},options:{en:o[0],ms:o[1],zh:o[2]},points,explanation,enabled:true});
export const QUESTIONS:Question[]=[
q('NUM-01',0,['A customer buys an RM 250 product with a 12% discount. What is the final price?','Pelanggan membeli produk RM 250 dengan diskaun 12%. Berapakah harga akhir?','顾客购买售价 RM 250 的产品，享有12%的折扣。最终价格是多少？'],[['RM 220','RM 230','RM 238','RM 280'],['RM 220','RM 230','RM 238','RM 280'],['RM 220','RM 230','RM 238','RM 280']],[100,0,0,0],'250 × 0.88 = RM 220.'),
q('NUM-02',0,['You earn 3% commission on RM 8,000 sales. What is your commission?','Anda menerima komisen 3% daripada jualan RM 8,000. Berapakah komisen anda?','销售额为 RM 8,000，佣金为3%。你能获得多少佣金？'],[['RM 24','RM 240','RM 800','RM 2,400'],['RM 24','RM 240','RM 800','RM 2,400'],['RM 24','RM 240','RM 800','RM 2,400']],[0,100,0,0],'8,000 × 0.03 = RM 240.'),
q('NUM-03',0,['Sales rose from RM 4,000 to RM 5,000. What was the percentage increase?','Jualan meningkat daripada RM 4,000 kepada RM 5,000. Berapakah peratus peningkatan?','销售额从 RM 4,000 增至 RM 5,000。增长率是多少？'],[['20%','25%','50%','10%'],['20%','25%','50%','10%'],['20%','25%','50%','10%']],[0,100,0,0],'1,000 ÷ 4,000 × 100 = 25%.'),
q('LOG-01',1,['All priority leads have verified contact details. Lead A has no verified contact details. What follows?','Semua prospek keutamaan mempunyai butiran hubungan yang disahkan. Butiran prospek A belum disahkan. Apakah kesimpulannya?','所有优先销售线索都有已验证的联系方式。线索A没有已验证的联系方式。可得出什么结论？'],[['A is a priority lead','A is not a priority lead','A will never buy','A has been contacted'],['A ialah prospek keutamaan','A bukan prospek keutamaan','A tidak akan membeli','A telah dihubungi'],['A是优先线索','A不是优先线索','A永远不会购买','A已被联系']],[0,100,0,0],'A does not meet the necessary condition for priority status.'),
q('LOG-02',1,['Visits follow this rule: call before visiting; verify stock before calling. What is the correct order?','Peraturan lawatan: telefon sebelum melawat; semak stok sebelum menelefon. Apakah urutan yang betul?','拜访规则：先打电话再拜访；先核实库存再打电话。正确的顺序是什么？'],[['Visit → call → stock','Call → stock → visit','Stock → call → visit','Stock → visit → call'],['Lawat → telefon → stok','Telefon → stok → lawat','Stok → telefon → lawat','Stok → lawat → telefon'],['拜访 → 电话 → 库存','电话 → 库存 → 拜访','库存 → 电话 → 拜访','库存 → 拜访 → 电话']],[0,0,100,0],'Both prerequisites must be satisfied in order.'),
q('LOG-03',1,['The daily follow-up targets are 4, 8, 12, 16. If the pattern continues, what is next?','Sasaran susulan harian ialah 4, 8, 12, 16. Jika pola diteruskan, apakah nombor seterusnya?','每日跟进目标为4、8、12、16。按照这个规律，下一个数字是什么？'],[['18','20','24','32'],['18','20','24','32'],['18','20','24','32']],[0,100,0,0],'The target increases by four each day.'),
q('SJT-01',2,['A customer says your price is 10% higher than a competitor’s. What do you do first?','Pelanggan berkata harga anda 10% lebih tinggi daripada pesaing. Apakah tindakan pertama anda?','顾客说你的价格比竞争对手高10%。你首先会怎么做？'],[['Promise an unapproved discount','Ask which offer they are comparing and what matters most','Say the competitor is unreliable','Repeat the product features'],['Janjikan diskaun tanpa kelulusan','Tanya tawaran yang dibandingkan dan keutamaan pelanggan','Katakan pesaing tidak boleh dipercayai','Ulang ciri produk'],['承诺未经批准的折扣','询问对比的报价及顾客最重视的需求','说竞争对手不可靠','重复介绍产品特点']],[0,100,0,30],'Clarify needs and like-for-like terms before proposing a solution.'),
q('SJT-02',2,['A customer is upset about a delayed delivery. What is the best first response?','Pelanggan marah kerana penghantaran lewat. Apakah respons awal yang terbaik?','顾客因延迟交货而生气。最佳的第一步回应是什么？'],[['Blame logistics','Promise delivery today without checking','Acknowledge the impact, check the order and agree a follow-up time','Avoid the call'],['Salahkan logistik','Janji hantar hari ini tanpa semakan','Akui kesannya, semak pesanan dan tetapkan masa susulan','Elakkan panggilan'],['责怪物流部门','未经核实便承诺今天送达','承认造成的影响，核实订单并约定跟进时间','回避电话']],[0,20,100,0],'Ownership, verification and a realistic next step protect trust.'),
q('SJT-03',2,['A customer asks you to hide a fee in the quotation. What do you do?','Pelanggan meminta anda menyembunyikan fi dalam sebut harga. Apakah tindakan anda?','顾客要求你在报价中隐瞒一项费用。你会怎么做？'],[['Hide it to close the deal','Explain all fees clearly and offer approved alternatives','Ask a colleague to hide it','Ignore the fee question'],['Sembunyikan untuk menutup jualan','Terangkan semua fi dan tawarkan alternatif yang diluluskan','Minta rakan menyembunyikannya','Abaikan soalan fi'],['为成交而隐瞒','明确解释全部费用，并提供获批的替代方案','让同事隐瞒','忽略费用问题']],[0,100,0,0],'Transparent pricing supports an informed customer decision.'),
q('PRO-01',3,['You have two hours and three customer visits. One urgent customer is 90 minutes away. What should you do first?','Anda mempunyai dua jam untuk tiga lawatan. Seorang pelanggan yang mendesak berada 90 minit perjalanan. Apakah langkah pertama?','你有两小时安排三次客户拜访。一位急需帮助的顾客距离你90分钟。你首先会怎么做？'],[['Drive immediately','Confirm urgency and explore a call or nearby colleague','Cancel every visit','Promise to reach everyone'],['Terus memandu','Sahkan keperluan segera dan cuba panggilan atau bantuan rakan berdekatan','Batalkan semua lawatan','Janji bertemu semua pelanggan'],['立即开车过去','确认紧急程度，考虑电话或附近同事协助','取消所有拜访','承诺拜访所有客户']],[20,100,0,0],'Gather the missing constraints before committing travel time.'),
q('PRO-02',3,['A popular product is out of stock and your customer needs it tomorrow. What is the best next step?','Produk popular kehabisan stok dan pelanggan memerlukannya esok. Apakah langkah terbaik?','热销产品缺货，顾客明天就需要。最佳下一步是什么？'],[['Promise stock will arrive','Check alternative stock locations and acceptable substitutes','Ask the customer to wait indefinitely','Close the order as delivered'],['Janji stok akan tiba','Semak stok lokasi lain dan pengganti yang boleh diterima','Minta pelanggan menunggu tanpa tempoh','Tandakan pesanan telah dihantar'],['承诺库存会到','核查其他地点库存及可接受的替代品','让顾客无限期等待','将订单标记为已交付']],[0,100,0,0],'Test feasible alternatives and communicate verified options.'),
q('PRO-03',3,['Conversion dropped this week. Which first step best helps find the cause?','Kadar penukaran menurun minggu ini. Langkah awal manakah paling membantu mencari punca?','本周转化率下降。哪一个初步行动最有助于找出原因？'],[['Double all discounts','Compare lead sources, funnel stages and sample sizes','Replace the whole sales team','Assume demand has disappeared'],['Gandakan semua diskaun','Banding sumber prospek, peringkat corong dan saiz sampel','Ganti seluruh pasukan','Anggap permintaan telah hilang'],['把所有折扣翻倍','比较线索来源、漏斗阶段和样本量','更换整个销售团队','假设需求已经消失']],[0,100,0,0],'Segment the evidence before choosing an intervention.'),
q('SELF-01',4,['When I am behind target and working independently, I am most likely to…','Apabila ketinggalan sasaran dan bekerja sendiri, saya paling cenderung untuk…','独立工作且落后于目标时，我最有可能……'],[['Wait for my manager to check','Review my pipeline and set specific daily actions','Stay busy without checking outcomes','Focus only on easy tasks'],['Tunggu pengurus menyemak','Semak saluran jualan dan tetapkan tindakan harian khusus','Sibukkan diri tanpa menyemak hasil','Fokus hanya pada tugas mudah'],['等主管来检查','检查销售管道并制定具体的每日行动','保持忙碌但不检查结果','只做容易的任务']],[0,100,20,20],'Self-report only: probe for an actual example of planning and follow-through.'),
q('SELF-02',4,['When a sales approach fails repeatedly, I usually…','Apabila pendekatan jualan gagal berulang kali, saya biasanya…','一种销售方式反复失败时，我通常……'],[['Keep repeating it unchanged','Avoid discussing it','Ask for feedback and test one specific improvement','Wait for someone else to fix it'],['Ulang tanpa perubahan','Elak membincangkannya','Minta maklum balas dan uji satu penambahbaikan khusus','Tunggu orang lain membaikinya'],['不做改变地重复','回避讨论','寻求反馈并测试一项具体改进','等别人解决']],[20,0,100,0],'Self-report only: look for evidence of learning and an observable change.'),
q('SELF-03',4,['When I commit to a follow-up, I usually…','Apabila berjanji membuat susulan, saya biasanya…','承诺跟进后，我通常……'],[['Rely on memory','Record a due date and check completion','Wait for the customer to remind me','Only follow up when the manager asks'],['Bergantung pada ingatan','Catat tarikh akhir dan semak pelaksanaan','Tunggu pelanggan mengingatkan','Susul hanya apabila pengurus meminta'],['依靠记忆','记录截止日期并检查完成情况','等顾客提醒','只在主管要求时跟进']],[30,100,0,0],'Self-report only: validate how the candidate tracks commitments.'),
q('DIG-01',5,['Dashboard: North — 20 leads, 5 sales. South — 40 leads, 8 sales. Which has the higher conversion rate?','Papan pemuka: Utara — 20 prospek, 5 jualan. Selatan — 40 prospek, 8 jualan. Yang manakah mempunyai kadar penukaran lebih tinggi?','仪表板：北区20条线索、5笔成交；南区40条线索、8笔成交。哪个地区转化率更高？'],[['North: 25%','South: 20%','Equal','Cannot calculate'],['Utara: 25%','Selatan: 20%','Sama','Tidak boleh dikira'],['北区：25%','南区：20%','相同','无法计算']],[100,0,0,0],'North: 5/20 = 25%; South: 8/40 = 20%.'),
q('DIG-02',5,['A CRM shows the same customer twice, with different phone numbers. What should you do first?','CRM menunjukkan pelanggan sama dua kali dengan nombor telefon berlainan. Apakah tindakan pertama?','CRM中同一位顾客出现两次，电话号码不同。你首先会怎么做？'],[['Delete both records','Verify the details and follow the duplicate-merge process','Call both numbers repeatedly','Ignore the duplicate'],['Padam kedua-duanya','Sahkan butiran dan ikut proses gabung rekod pendua','Telefon kedua-dua nombor berulang kali','Abaikan rekod pendua'],['删除两条记录','核实信息并按流程合并重复记录','反复拨打两个号码','忽略重复记录']],[0,100,0,20],'Verify accuracy before changing customer records.'),
q('DIG-03',5,['Dashboard: 12 follow-ups are overdue; 4 new leads arrived. What is the most useful next action?','Papan pemuka: 12 susulan lewat; 4 prospek baharu diterima. Apakah tindakan seterusnya paling berguna?','仪表板：12次跟进已逾期，新收到4条线索。最有用的下一步是什么？'],[['Ignore overdue work','Prioritise by urgency and value, then schedule and record follow-ups','Mark every follow-up complete','Export customer data to a public folder'],['Abaikan kerja lewat','Utamakan mengikut keperluan dan nilai, jadualkan serta rekod susulan','Tanda semua susulan selesai','Eksport data pelanggan ke folder awam'],['忽略逾期任务','按紧急程度和价值排序，安排并记录跟进','把所有跟进标记为完成','将客户数据导出到公共文件夹']],[0,100,0,0],'Use the dashboard to prioritise action while protecting data.'),
];

